// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxwXxGqD08z1PpPu2LvDD9G0_4wRW8isc',
    appId: '1:277396784849:web:cd8e023817006e33e367f0',
    messagingSenderId: '277396784849',
    projectId: 'quizzzzz-24bd7',
    authDomain: 'quizzzzz-24bd7.firebaseapp.com',
    storageBucket: 'quizzzzz-24bd7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhEqdwep1SN3BAMQfZBkDVhzBhy2AkMiU',
    appId: '1:277396784849:android:2065240074399a99e367f0',
    messagingSenderId: '277396784849',
    projectId: 'quizzzzz-24bd7',
    storageBucket: 'quizzzzz-24bd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVxieHHC8m0SMqXNyQB-6LIY2j9jj7Br0',
    appId: '1:277396784849:ios:d8743fe6ee2125d4e367f0',
    messagingSenderId: '277396784849',
    projectId: 'quizzzzz-24bd7',
    storageBucket: 'quizzzzz-24bd7.firebasestorage.app',
    iosBundleId: 'com.example.devaquiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVxieHHC8m0SMqXNyQB-6LIY2j9jj7Br0',
    appId: '1:277396784849:ios:d8743fe6ee2125d4e367f0',
    messagingSenderId: '277396784849',
    projectId: 'quizzzzz-24bd7',
    storageBucket: 'quizzzzz-24bd7.firebasestorage.app',
    iosBundleId: 'com.example.devaquiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxwXxGqD08z1PpPu2LvDD9G0_4wRW8isc',
    appId: '1:277396784849:web:34774901eb28ccb5e367f0',
    messagingSenderId: '277396784849',
    projectId: 'quizzzzz-24bd7',
    authDomain: 'quizzzzz-24bd7.firebaseapp.com',
    storageBucket: 'quizzzzz-24bd7.firebasestorage.app',
  );
}
